### PR TITLE
Support fragment content

### PR DESCRIPTION
**Pull request by paf31**
This is useful for handling encapsulated pixel data.

### CODE REVIEW

**Comment by spencerjanssen** [comment]
Hello,

Do you plan on merging this branch and/or releasing it any time soon?  We've used it in a project over here where we need to process DICOMs that contain pixel data.  It works quite well for our purposes, but it'd be nice to depend on a Hackage release rather than fetching from git.

Thanks for the code,
Spencer

**Comment by paf31** [comment]
My main concern with this was finishing testing. I've done a little testing myself, but if you're using this and are happy with it in its current state, I'll wrap it up and push it to Hackage.

**Comment by spencerjanssen** [comment]
It's worked well for us so far.  I should note that we're not actually using any of the pixel data, just parsing files that contain it.

**Comment by paf31** [comment]
Ah ok, then yes, I'd expect the old code to still fail in some cases (encapsulated pixel data, I suppose).

**Comment by paf31** [comment]
Uploaded as `dicom-0.3.0.0`.

**Pull request merged**
